name: GeyserModelEngine
version: '${project.version}'
main: io.rivrs.geysermodelengine.GeyserModelEngine
authors:
  - Rivrs
  - Roch Blondiaux
api-version: '1.19'
depend:
  - ModelEngine
  - floodgate
  - BedrockCore
  - packetevents